/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 08-Apr-2023 16:52:52
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 101;
const int16_T B[101] = {
        0,      0,      0,      0,     -1,      0,      2,      5,     10,
       15,     20,     22,     21,     15,      7,      0,     -3,      3,
       20,     48,     82,    113,    128,    118,     75,      0,    -98,
     -201,   -285,   -327,   -313,   -243,   -136,    -28,     33,      0,
     -161,   -455,   -856,  -1297,  -1685,  -1917,  -1897,  -1567,   -917,
        0,   1075,   2159,   3087,   3712,   3933,   3712,   3087,   2159,
     1075,      0,   -917,  -1567,  -1897,  -1917,  -1685,  -1297,   -856,
     -455,   -161,      0,     33,    -28,   -136,   -243,   -313,   -327,
     -285,   -201,    -98,      0,     75,    118,    128,    113,     82,
       48,     20,      3,     -3,      0,      7,     15,     21,     22,
       20,     15,     10,      5,      2,      0,     -1,      0,      0,
        0,      0
};
