function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, YData4)
%CREATEFIGURE(XData1, YData1, XData2, YData2, XData3, YData3, YData4)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  YDATA4:  line ydata

%  Auto-generated by MATLAB on 01-Jun-2023 14:14:06

% Create figure
figure1 = figure('PaperSize',[6 3],'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.1378125 0.488677157652474 0.7671875 0.40755414269275]);

% Create line
line(XData1,YData1,'Visible','off','Parent',axes1);

% Create hggroup
hggroup1 = hggroup('Parent',axes1,'DisplayName','H');

% Create line
line(XData2,YData2,'Parent',hggroup1,'LineWidth',2,'Color',[0 0.447 0.741]);

% Create ylabel
ylabel('Magnitud (dB)','HitTest','off','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[10 10000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-15 0]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XColor',[0.4 0.4 0.4],'XMinorTick','on','XScale','log',...
    'XTickLabel','','YColor',[0.4 0.4 0.4]);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.1378125 0.11 0.7671875 0.361415937859609]);

% Create line
line(XData3,YData3,'Visible','off','Parent',axes2);

% Create hggroup
hggroup2 = hggroup('Parent',axes2,'DisplayName','H');

% Create line
line(XData2,YData4,'Parent',hggroup2,'LineWidth',2,'Color',[0 0.447 0.741]);

% Create ylabel
ylabel('Fase (deg)','HitTest','off','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[10 10000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-40.4 0.4]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'XColor',[0.4 0.4 0.4],'XMinorTick','on','XScale','log','YColor',...
    [0.4 0.4 0.4],'YTick',[-40 -30 -20 -10 0]);
% Create xlabel
xlabel('Frecuencia (T_s = .001 s)  (rad/s)','HitTest','off',...
    'Units','pixels',...
    'HorizontalAlignment','center',...
    'FontSize',11,...
    'Visible','on');

% Create title
title('Diagrama de Bode','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',11);

