/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 01-Jun-2023 17:44:58
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,2,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.2823472326406,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
     0.4606491465877,                 0,                 0 
  },
  {
                   1,                 1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,2,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.2094387997766,   0.3388277303392 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1, -0.07870170682462,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
